### ISSUE TITLE
Upgrade Angular to supported version

### ISSUE THREAD

**Issue by JakeLo123** [FusionAuth/fusionauth-angular-sdk#5]
### Description
The SDK is using Angular `v13`, which is unsupported.
We should upgrade to a [supported version](https://angular.io/guide/versions).

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by david-chalk** [comment]
We should aim for the latest version. Though going from v13 to v17 may be too huge of a jump, so we may want to upgrade in a stepwise fashion, ie v13 -> one-or-more-intermediary-versions -> v17.

**Comment by lyleschemmerling** [comment]
What strategy would you recommend for keeping relevant and up to date with this library? The angular release cadence is a new major release every six months. Should we be releasing a new version in lock step with each angular release even if we have not changed the content? If not how else can we handle this situation?

**Comment by david-chalk** [comment]
@lyleschemmerling I would recommend keeping as up-to-date as reasonably as possible, regardless if the content has changed. Especially considering that the recommended upgrade path is a step-wise fashion.  I.e. If going from v13 to v17, Angular recommends upgrading from v13 to v14 to v15 to v16 to v17.

So we might as well just take the time to upgrade when a major release is officially out, otherwise we're just deferring the same work till later anyway. Plus, it'll be easier to track which version introduced a breaking change for the SDK. It's possible that we test and think everything is good when going from v13 to v17 but then if we get reports of something being broken, we won't know for sure which version migration caused the issue (and so it'll be harder to figure out what the cause and solution are).

Angular actually has a super convenient upgrade guide with officially recommended steps that we can follow:
https://update.angular.io/?v=13.0-17.0

**Comment by JakeLo123** [comment]
Closing this because we've reached 16, which is LTS.
https://github.com/FusionAuth/fusionauth-angular-sdk/pull/16
